# Generated by Django 4.1.7 on 2023-02-19 17:05

import api.model_fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('params', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='LayerAccessibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessibility_type', models.CharField(blank=True, choices=[('File', 'File'), ('DB', 'Database'), ('D_DB', 'Django Database Key')], max_length=30, null=True)),
                ('params', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='LayerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='LayerQualityLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('extent', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[-20037508.3427892, -20037508.3427892, 20037508.3427892, 20037508.3427892], size=None)),
                ('layers', models.JSONField()),
                ('srid', models.IntegerField(default=3857)),
                ('units', models.CharField(choices=[('m', 'meter'), ('ft', 'feet'), ('dd', 'decimal_degree')], default='m', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LayerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=40, unique=True)),
                ('app_label', models.CharField(default='gis', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('layer_name', models.CharField(max_length=100)),
                ('srid', models.IntegerField(blank=True, null=True)),
                ('proj4', models.TextField(blank=True, null=True)),
                ('extent', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('data_model', models.CharField(blank=True, choices=[('R', 'Raster'), ('V', 'Vector')], max_length=30, null=True)),
                ('vector_type', models.CharField(blank=True, choices=[('T', 'TIN'), ('N', 'Network'), ('Geom', 'Geometry'), ('Cnt', 'Contour'), ('Oth', 'Other')], max_length=20, null=True)),
                ('raster_type', models.CharField(blank=True, choices=[('S', 'Satellite'), ('DEM', 'Digital Elevation Model'), ('DSM', 'Digital Surface Model'), ('Surf', 'Surface'), ('Classification', 'Classification'), ('Oth', 'Oth')], max_length=20, null=True)),
                ('geom_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('layer_styling', models.JSONField(blank=True, null=True)),
                ('zoom_range', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0, 30], size=None)),
                ('dataset_info', models.JSONField(blank=True, null=True)),
                ('uploaded_by', api.model_fields.UserForeignKey(blank=True, null=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map_viewer.layercategory')),
                ('layer_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map_viewer.layeraccessibility')),
                ('quality_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map_viewer.layerqualitylevel')),
            ],
        ),
    ]
