# Generated by Django 4.1.7 on 2023-02-22 06:22

import api.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', api.model_fields.UserForeignKey(blank=True, null=True)),
                ('remote_address', models.CharField(max_length=100)),
                ('server_hostname', models.CharField(max_length=100)),
                ('request_method', models.CharField(max_length=10)),
                ('request_path', models.CharField(max_length=100)),
                ('request_params', models.JSONField(blank=True, null=True)),
                ('run_time', models.PositiveIntegerField()),
                ('log_type', models.CharField(choices=[('Err', 'Error'), ('Info', 'Info'), ('Warn', 'Warning')], max_length=10)),
                ('request_body', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
                ('stack_trace', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
